services:
  tika:
    image: apache/tika:3.2.3.0
    container_name: doub-chat-tika
    ports:
      - "127.0.0.1:9998:9998"
    restart: unless-stopped
    networks:
      - doub-chat

networks:
  doub-chat:
    external: true
    name: doub-chat-network
